#!/bin/sh
# This script has one line for each known working toolchain
# for this architecture.  Uncomment the one you want.
# Generated by generate-demo.pl from buildlogs/all.dats.txt

# based on demo-powerpc-603.sh

set -ex
TARBALLS_DIR=`pwd`/downloads
RESULT_TOP=`pwd`/crosstool
export TARBALLS_DIR RESULT_TOP
GCC_LANGUAGES="c"
export GCC_LANGUAGES

# Really, you should do the mkdir before running this,
# and chown /opt/crosstool to yourself so you don't need to run as root.
mkdir -p $RESULT_TOP

eval `cat powerpc-603.dat my-gcc-4.1.0-glibc-2.3.6-tls.dat` sh all.sh --notest

echo Done.
